// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CounterState struct {
	ID    int32
	Total int64
}

type UserAchievement struct {
	UserSub       string
	AchievementID string
	UnlockedAt    time.Time
}

type UserClick struct {
	UserSub string
	Clicks  int64
}

type UserProfile struct {
	UserSub     string
	DisplayName string
	UpdatedAt   time.Time
}

type UserStreak struct {
	UserSub  string
	CurDays  int32
	BestDays int32
	LastDay  string
}

type UserWeeklyClick struct {
	UserSub   string
	WeekStart pgtype.Date
	Clicks    int64
}
