// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type CounterOutbox struct {
	ID        string
	Clicks    int64
	CreatedAt time.Time
}

type UserAchievement struct {
	UserSub       string
	AchievementID string
	UnlockedAt    time.Time
}

type UserClick struct {
	UserSub string
	Clicks  int64
}
