// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type UserAchievement struct {
	UserSub       string
	AchievementID string
	UnlockedAt    time.Time
}

type UserClick struct {
	UserSub string
	Clicks  int64
}

type UserProfile struct {
	UserSub     string
	DisplayName string
	UpdatedAt   time.Time
}

type UserWeeklyClick struct {
	UserSub   string
	WeekStart pgtype.Date
	Clicks    int64
}
