// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const countOutbox = `-- name: CountOutbox :one
SELECT COUNT(*) AS count FROM counter_outbox
`

func (q *Queries) CountOutbox(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOutbox)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count FROM user_clicks
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOutboxBefore = `-- name: DeleteOutboxBefore :exec
DELETE FROM counter_outbox WHERE created_at <= $1
`

func (q *Queries) DeleteOutboxBefore(ctx context.Context, createdAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteOutboxBefore, createdAt)
	return err
}

const deleteOutboxByID = `-- name: DeleteOutboxByID :exec
DELETE FROM counter_outbox WHERE id = $1
`

func (q *Queries) DeleteOutboxByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOutboxByID, id)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO counter_outbox (id, clicks) VALUES ($1, $2)
`

type InsertOutboxParams struct {
	ID     string
	Clicks int64
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.Exec(ctx, insertOutbox, arg.ID, arg.Clicks)
	return err
}

const insertOutboxAt = `-- name: InsertOutboxAt :exec
INSERT INTO counter_outbox (id, clicks, created_at) VALUES ($1, $2, $3)
`

type InsertOutboxAtParams struct {
	ID        string
	Clicks    int64
	CreatedAt time.Time
}

// Test support: sets created_at explicitly. The production InsertOutbox always
// DEFAULTs created_at to now(); this exists only for integration-test fixtures
// that need a backdated row to exercise the sweeper's time window.
func (q *Queries) InsertOutboxAt(ctx context.Context, arg InsertOutboxAtParams) error {
	_, err := q.db.Exec(ctx, insertOutboxAt, arg.ID, arg.Clicks, arg.CreatedAt)
	return err
}

const insertUserAchievement = `-- name: InsertUserAchievement :one
INSERT INTO user_achievements (user_sub, achievement_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING unlocked_at
`

type InsertUserAchievementParams struct {
	UserSub       string
	AchievementID string
}

func (q *Queries) InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUserAchievement, arg.UserSub, arg.AchievementID)
	var unlocked_at time.Time
	err := row.Scan(&unlocked_at)
	return unlocked_at, err
}

const listOutboxBefore = `-- name: ListOutboxBefore :many
SELECT id FROM counter_outbox WHERE created_at <= $1
`

func (q *Queries) ListOutboxBefore(ctx context.Context, createdAt time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, listOutboxBefore, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepableOutbox = `-- name: ListSweepableOutbox :many
SELECT id, clicks, created_at FROM counter_outbox
WHERE created_at < now() - interval '30 seconds'
ORDER BY created_at
LIMIT $1
`

func (q *Queries) ListSweepableOutbox(ctx context.Context, limit int32) ([]CounterOutbox, error) {
	rows, err := q.db.Query(ctx, listSweepableOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CounterOutbox{}
	for rows.Next() {
		var i CounterOutbox
		if err := rows.Scan(&i.ID, &i.Clicks, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT achievement_id, unlocked_at FROM user_achievements WHERE user_sub = $1
`

type ListUserAchievementsRow struct {
	AchievementID string
	UnlockedAt    time.Time
}

func (q *Queries) ListUserAchievements(ctx context.Context, userSub string) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAchievements, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAchievementsRow{}
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(&i.AchievementID, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserClicks = `-- name: SumUserClicks :one
SELECT COALESCE(SUM(clicks), 0)::bigint AS total FROM user_clicks
`

func (q *Queries) SumUserClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserClicks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const sumUserClicksNow = `-- name: SumUserClicksNow :one
SELECT COALESCE(SUM(clicks), 0)::bigint AS total, now()::timestamptz AS now FROM user_clicks
`

type SumUserClicksNowRow struct {
	Total int64
	Now   time.Time
}

func (q *Queries) SumUserClicksNow(ctx context.Context) (SumUserClicksNowRow, error) {
	row := q.db.QueryRow(ctx, sumUserClicksNow)
	var i SumUserClicksNowRow
	err := row.Scan(&i.Total, &i.Now)
	return i, err
}

const upsertUserClicks = `-- name: UpsertUserClicks :one
INSERT INTO user_clicks AS u (user_sub, clicks) VALUES ($1, $2)
ON CONFLICT (user_sub) DO UPDATE SET clicks = u.clicks + $2
RETURNING clicks
`

type UpsertUserClicksParams struct {
	UserSub string
	Clicks  int64
}

func (q *Queries) UpsertUserClicks(ctx context.Context, arg UpsertUserClicksParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserClicks, arg.UserSub, arg.Clicks)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}
