// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpsertUserClicks = `-- name: BatchUpsertUserClicks :exec
INSERT INTO user_clicks AS u (user_sub, clicks)
SELECT unnest($1::text[]), unnest($2::bigint[])
ON CONFLICT (user_sub) DO UPDATE SET clicks = EXCLUDED.clicks
`

type BatchUpsertUserClicksParams struct {
	Subs   []string
	Clicks []int64
}

// Absolute set (not increment): the caller passes the authoritative Redis
// ZSET score, so re-running a flush is idempotent.
func (q *Queries) BatchUpsertUserClicks(ctx context.Context, arg BatchUpsertUserClicksParams) error {
	_, err := q.db.Exec(ctx, batchUpsertUserClicks, arg.Subs, arg.Clicks)
	return err
}

const batchUpsertUserProfile = `-- name: BatchUpsertUserProfile :exec
INSERT INTO user_profile AS p (user_sub, display_name, updated_at)
SELECT unnest($1::text[]), unnest($2::text[]), now()
ON CONFLICT (user_sub) DO UPDATE SET display_name = EXCLUDED.display_name, updated_at = now()
`

type BatchUpsertUserProfileParams struct {
	Subs  []string
	Names []string
}

func (q *Queries) BatchUpsertUserProfile(ctx context.Context, arg BatchUpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, batchUpsertUserProfile, arg.Subs, arg.Names)
	return err
}

const batchUpsertUserWeeklyClicks = `-- name: BatchUpsertUserWeeklyClicks :exec
INSERT INTO user_weekly_clicks AS w (user_sub, week_start, clicks)
SELECT unnest($1::text[]), $2::date, unnest($3::bigint[])
ON CONFLICT (user_sub, week_start) DO UPDATE SET clicks = EXCLUDED.clicks
`

type BatchUpsertUserWeeklyClicksParams struct {
	Subs      []string
	WeekStart pgtype.Date
	Clicks    []int64
}

func (q *Queries) BatchUpsertUserWeeklyClicks(ctx context.Context, arg BatchUpsertUserWeeklyClicksParams) error {
	_, err := q.db.Exec(ctx, batchUpsertUserWeeklyClicks, arg.Subs, arg.WeekStart, arg.Clicks)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count FROM user_clicks
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserClicks = `-- name: GetUserClicks :one
SELECT clicks FROM user_clicks WHERE user_sub = $1
`

func (q *Queries) GetUserClicks(ctx context.Context, userSub string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserClicks, userSub)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}

const insertUserAchievement = `-- name: InsertUserAchievement :one
INSERT INTO user_achievements (user_sub, achievement_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING unlocked_at
`

type InsertUserAchievementParams struct {
	UserSub       string
	AchievementID string
}

func (q *Queries) InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUserAchievement, arg.UserSub, arg.AchievementID)
	var unlocked_at time.Time
	err := row.Scan(&unlocked_at)
	return unlocked_at, err
}

const insertUserAchievementAt = `-- name: InsertUserAchievementAt :exec
INSERT INTO user_achievements (user_sub, achievement_id, unlocked_at) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertUserAchievementAtParams struct {
	UserSub       string
	AchievementID string
	UnlockedAt    time.Time
}

func (q *Queries) InsertUserAchievementAt(ctx context.Context, arg InsertUserAchievementAtParams) error {
	_, err := q.db.Exec(ctx, insertUserAchievementAt, arg.UserSub, arg.AchievementID, arg.UnlockedAt)
	return err
}

const listAllUserClicks = `-- name: ListAllUserClicks :many
SELECT user_sub, clicks FROM user_clicks
`

func (q *Queries) ListAllUserClicks(ctx context.Context) ([]UserClick, error) {
	rows, err := q.db.Query(ctx, listAllUserClicks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserClick{}
	for rows.Next() {
		var i UserClick
		if err := rows.Scan(&i.UserSub, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProfileNames = `-- name: ListProfileNames :many
SELECT user_sub, display_name FROM user_profile WHERE user_sub = ANY($1::text[])
`

type ListProfileNamesRow struct {
	UserSub     string
	DisplayName string
}

func (q *Queries) ListProfileNames(ctx context.Context, dollar_1 []string) ([]ListProfileNamesRow, error) {
	rows, err := q.db.Query(ctx, listProfileNames, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProfileNamesRow{}
	for rows.Next() {
		var i ListProfileNamesRow
		if err := rows.Scan(&i.UserSub, &i.DisplayName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT achievement_id, unlocked_at FROM user_achievements WHERE user_sub = $1
`

type ListUserAchievementsRow struct {
	AchievementID string
	UnlockedAt    time.Time
}

func (q *Queries) ListUserAchievements(ctx context.Context, userSub string) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAchievements, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAchievementsRow{}
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(&i.AchievementID, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWeekUserClicks = `-- name: ListWeekUserClicks :many
SELECT user_sub, clicks FROM user_weekly_clicks WHERE week_start = $1
`

type ListWeekUserClicksRow struct {
	UserSub string
	Clicks  int64
}

func (q *Queries) ListWeekUserClicks(ctx context.Context, weekStart pgtype.Date) ([]ListWeekUserClicksRow, error) {
	rows, err := q.db.Query(ctx, listWeekUserClicks, weekStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWeekUserClicksRow{}
	for rows.Next() {
		var i ListWeekUserClicksRow
		if err := rows.Scan(&i.UserSub, &i.Clicks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserClicks = `-- name: SumUserClicks :one
SELECT COALESCE(SUM(clicks), 0)::bigint AS total FROM user_clicks
`

func (q *Queries) SumUserClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserClicks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertUserClicks = `-- name: UpsertUserClicks :one
INSERT INTO user_clicks AS u (user_sub, clicks) VALUES ($1, $2)
ON CONFLICT (user_sub) DO UPDATE SET clicks = u.clicks + $2
RETURNING clicks
`

type UpsertUserClicksParams struct {
	UserSub string
	Clicks  int64
}

func (q *Queries) UpsertUserClicks(ctx context.Context, arg UpsertUserClicksParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserClicks, arg.UserSub, arg.Clicks)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :exec
INSERT INTO user_profile AS p (user_sub, display_name, updated_at) VALUES ($1, $2, now())
ON CONFLICT (user_sub) DO UPDATE SET display_name = $2, updated_at = now()
`

type UpsertUserProfileParams struct {
	UserSub     string
	DisplayName string
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) error {
	_, err := q.db.Exec(ctx, upsertUserProfile, arg.UserSub, arg.DisplayName)
	return err
}

const upsertUserWeeklyClicks = `-- name: UpsertUserWeeklyClicks :one
INSERT INTO user_weekly_clicks AS w (user_sub, week_start, clicks) VALUES ($1, $2, $3)
ON CONFLICT (user_sub, week_start) DO UPDATE SET clicks = w.clicks + $3
RETURNING clicks
`

type UpsertUserWeeklyClicksParams struct {
	UserSub   string
	WeekStart pgtype.Date
	Clicks    int64
}

func (q *Queries) UpsertUserWeeklyClicks(ctx context.Context, arg UpsertUserWeeklyClicksParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserWeeklyClicks, arg.UserSub, arg.WeekStart, arg.Clicks)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}
