// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count FROM user_clicks
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUserAchievement = `-- name: InsertUserAchievement :one
INSERT INTO user_achievements (user_sub, achievement_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
RETURNING unlocked_at
`

type InsertUserAchievementParams struct {
	UserSub       string
	AchievementID string
}

func (q *Queries) InsertUserAchievement(ctx context.Context, arg InsertUserAchievementParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, insertUserAchievement, arg.UserSub, arg.AchievementID)
	var unlocked_at time.Time
	err := row.Scan(&unlocked_at)
	return unlocked_at, err
}

const listUserAchievements = `-- name: ListUserAchievements :many
SELECT achievement_id, unlocked_at FROM user_achievements WHERE user_sub = $1
`

type ListUserAchievementsRow struct {
	AchievementID string
	UnlockedAt    time.Time
}

func (q *Queries) ListUserAchievements(ctx context.Context, userSub string) ([]ListUserAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listUserAchievements, userSub)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAchievementsRow{}
	for rows.Next() {
		var i ListUserAchievementsRow
		if err := rows.Scan(&i.AchievementID, &i.UnlockedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserClicks = `-- name: SumUserClicks :one
SELECT COALESCE(SUM(clicks), 0)::bigint AS total FROM user_clicks
`

func (q *Queries) SumUserClicks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserClicks)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const upsertUserClicks = `-- name: UpsertUserClicks :one
INSERT INTO user_clicks AS u (user_sub, clicks) VALUES ($1, $2)
ON CONFLICT (user_sub) DO UPDATE SET clicks = u.clicks + $2
RETURNING clicks
`

type UpsertUserClicksParams struct {
	UserSub string
	Clicks  int64
}

func (q *Queries) UpsertUserClicks(ctx context.Context, arg UpsertUserClicksParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertUserClicks, arg.UserSub, arg.Clicks)
	var clicks int64
	err := row.Scan(&clicks)
	return clicks, err
}
